apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      nodeSelector:
        node: node2
      containers:
      - name: api-gateway
        image: 218828204349.dkr.ecr.us-east-2.amazonaws.com/apigateway:latest
        imagePullPolicy: Always
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 8188
          name: http
          protocol: TCP
        volumeMounts:
        - name: log-path
          mountPath: /var/log/als
      volumes:
      - name: log-path
        hostPath:
          path: /var/log/als

# service type LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
    k8s-app: api-gateway
  name: api-gateway
spec:
  ports:
  - port: 8188
    targetPort: 8188
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8188
    protocol: TCP
    name: https
  type: NodePort
  selector:
    app: api-gateway
