apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: compliance-service
  name: compliance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compliance-service
  template:
    metadata:
      labels:
        app: compliance-service
    spec:
      nodeSelector:
        node: node3
      containers:
      - name: compliance-service
        image: 218828204349.dkr.ecr.us-east-2.amazonaws.com/compliance-service:latest
        imagePullPolicy: Always
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 9211
          name: http
          protocol: TCP
        volumeMounts:
        - name: log-path
          mountPath: /var/log/als
        resources:
          requests:
            ephemeral-storage: "100Mi"
          limits:
            ephemeral-storage: "500Mi"
      volumes:
      - name: log-path
        hostPath:
          path: /var/log/als


# service type ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: compliance-service
    k8s-app: compliance-service
  name: compliance-service
spec:
  ports:
  - name: http
    port: 9211
    protocol: TCP
    targetPort: 9211
  type: ClusterIP
  selector:
    app: compliance-service
