apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: forex-service
  name: forex-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forex-service
  template:
    metadata:
      labels:
        app: forex-service
    spec:
      nodeSelector:
        node: node2
      containers:
      - name: forex-service
        image: 218828204349.dkr.ecr.us-east-2.amazonaws.com/forex-service:latest
        imagePullPolicy: Always
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 9002
          name: http
          protocol: TCP
        volumeMounts:
        - name: log-path
          mountPath: /var/log/als
      volumes:
      - name: log-path
        hostPath:
          path: /var/log/als

# service type ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: forex-service
    k8s-app: forex-service
  name: forex-service
spec:
  ports:
  - name: http
    port: 9002
    protocol: TCP
    targetPort: 9002
  type: ClusterIP
  selector:
    app: forex-service
