apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: master-database-management-service
  name: master-database-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-database-management-service
  template:
    metadata:
      labels:
        app: master-database-management-service
    spec:
      nodeSelector:
        node: node3
    
      containers:
      - name: master-database-management-service
        image: 218828204349.dkr.ecr.us-east-2.amazonaws.com/master-database-management-service:latest
        #image: 218828204349.dkr.ecr.eu-west-2.amazonaws.com/master-database-management-service-repo:latest
        imagePullPolicy: Always
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 8001
          name: http
          protocol: TCP
        volumeMounts:
        - name: log-path
          mountPath: /var/log/als
      volumes:
      - name: log-path
        hostPath:
          path: /var/log/als

# service type ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: master-database-management-service
    k8s-app: master-database-management-service
  name: master-database-management-service
spec:
  ports:
  - name: http
    port: 8001
    protocol: TCP
    targetPort: 8001
  type: ClusterIP
  selector:
    app: master-database-management-service
