apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-service
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      nodeSelector:
        node: node1  # Node Selection to Node 1
      containers:
      - name: product-service
        image: 218828204349.dkr.ecr.us-east-2.amazonaws.com/product-service:latest
        imagePullPolicy: Always
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 9083
          name: http
          protocol: TCP
        volumeMounts:
        - name: log-path
          mountPath: /var/log/als
      volumes:
      - name: log-path
        hostPath:
          path: /var/log/als
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-service
    k8s-app: product-service
  name: product-service
spec:
  ports:
  - name: http
    port: 9083
    protocol: TCP
    targetPort: 9083
  type: ClusterIP
  selector:
    app: product-service
