apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: search-service
  name: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      nodeSelector:
        node: node1
      containers:
      - name: search-service
        image: 218828204349.dkr.ecr.us-east-2.amazonaws.com/search-service:latest
        imagePullPolicy: Always
        env:
          - name: CLUSTER_NODES
            value: elasticsearch:9300
          - name: CLUSTER_HOST
            value: elasticsearch
          - name: REST_URI
            value: elasticsearch:9200
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 9191
          name: http
          protocol: TCP
        volumeMounts:
        - name: log-path
          mountPath: /var/log/als
      volumes:
      - name: log-path
        hostPath:
          path: /var/log/als

# service type ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: search-service
    k8s-app: search-service
  name: search-service
spec:
  ports:
  - name: http
    port: 9191
    protocol: TCP
    targetPort: 9191
  type: ClusterIP
  selector:
    app: search-service
