apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-management-service
  name: task-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-management-service
  template:
    metadata:
      labels:
        app: task-management-service
    spec:
      containers:
      - name: task-management-service
        image: 218828204349.dkr.ecr.us-east-2.amazonaws.com/task-management-service:1
        imagePullPolicy: Always
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 8222
          name: http
          protocol: TCP
        volumeMounts:
        - name: log-path
          mountPath: /var/log/als
      volumes:
      - name: log-path
        hostPath:
          path: /var/log/als

# service type ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-management-service
    k8s-app: task-management-service
  name: task-management-service
spec:
  ports:
  - name: http
    port: 8222
    protocol: TCP
    targetPort: 8222
  type: ClusterIP
  selector:
    app: task-management-service
