apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transport-service-v2
  name: transport-service-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transport-service-v2
  template:
    metadata:
      labels:
        app: transport-service-v2
    spec:
      containers:
        - name: transport-service-v2
          image: 218828204349.dkr.ecr.us-east-2.amazonaws.com/transport-service-v2:1
          imagePullPolicy: Always
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: als-db-secret
                  key: db-password
                
          ports:
            - containerPort: 9095
              name: http
              protocol: TCP
          volumeMounts:
            - name: log-path
              mountPath: /var/log/als
      volumes:
        - name: log-path
          hostPath:
            path: /var/log/als

# service type ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: transport-service-v2
    k8s-app: transport-service-v2
  name: transport-service-v2
spec:
  ports:
    - name: http
      port: 9095
      protocol: TCP
      targetPort: 9095
  type: ClusterIP
  selector:
    app: transport-service-v2
