apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workflow-service
  name: workflow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-service
  template:
    metadata:
      labels:
        app: workflow-service
    spec:
      nodeSelector:
        node: node3
      containers:
      - name: workflow-service
        image: 218828204349.dkr.ecr.us-east-2.amazonaws.com/workflow-service:1
        imagePullPolicy: Always
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 9900
          name: http
          protocol: TCP
        volumeMounts:
        - name: log-path
          mountPath: /var/log/als
      volumes:
      - name: log-path
        hostPath:
          path: /var/log/als

# service type ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: workflow-service
    k8s-app: workflow-service
  name: workflow-service
spec:
  ports:
  - name: http
    port: 9900
    protocol: TCP
    targetPort: 9900
  type: ClusterIP
  selector:
    app: workflow-service
