apiVersion: v1
kind: Service
metadata:
  name: my-cluster-kafka-brokers
  namespace: default
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
    - port: 9092
      name: kafka
  selector:
    app: kafka

---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster-kafka-bootstrap
  namespace: default
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      name: kafka
  selector:
    app: kafka

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: default
spec:
  serviceName: my-cluster-kafka-brokers
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 1001  # Bitnami Kafka runs as this group
      containers:
        - name: kafka
          image: bitnami/kafka:3.6
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: my-cluster-zookeeper-nodes:2181
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://my-cluster-kafka-bootstrap:9092
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp2
        resources:
          requests:
            storage: 40Gi
